image:
  repository: tccr.io/truecharts/homer
  tag: 22.11.2@sha256:0352803992e182f694ed9ae9dfd99f1d96a52d79a177dfdf9b7c94e6848c1143
  pullPolicy: IfNotPresent

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

env:
  INIT_ASSETS: true

service:
  main:
    ports:
      main:
        port: 10178
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/www/assets"

portal:
  enabled: true
