image:
  repository: tccr.io/truecharts/jellyseerr
  tag: 1.2.1@sha256:64ef1131b87c049fe8d47b6e8b9f5ceca81d1aa944ec3885600b650ea4d69ade
  pullPolicy: IfNotPresent

env:
  PORT: "{{ .Values.service.main.ports.main.port }}"
  # User Defined
  JELLYFIN_TYPE: ""
  LOG_LEVEL: "info"

service:
  main:
    ports:
      main:
        port: 10241

persistence:
  config:
    enabled: true
    mountPath: "/app/config"

portal:
  enabled: true
