image:
  repository: tccr.io/truecharts/qbittorrent
  pullPolicy: IfNotPresent
  tag: v4.4.5@sha256:246ecabd9d6893597449e7f62c35d541ffd029cda168b7957008ceec19e87972

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 10095
        targetPort: 8080
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 6881
        targetPort: 6881
  torrentudp:
    enabled: true
    ports:
      torrentudp:
        enabled: true
        port: 6881
        targetPort: 6881
        protocol: UDP

persistence:
  config:
    enabled: true
    mountPath: "/config"

additionalVolumes:
  - name: qbittorrent-scripts
    emptyDir: {}
    ## When you want to enable automatic port configuration at startup, adjust this to:
    # configMap:
    #   name: <RELEASENAME>-scripts
    #   defaultMode: 511

additionalVolumeMounts:
  - mountPath: "/config/custom-cont-init.d"
    name: qbittorrent-scripts

portal:
  enabled: true
