image:
  repository: tccr.io/truecharts/prowlarr
  tag: 1.0.1.2210@sha256:79e800fda0c8bb9e5d55f42eb41dd05ff007ba80954520d30ad8fd990e3f25ee
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 9696
        targetPort: 9696

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
